### ISSUE TITLE
[Bug] Camel case conversion for attribute list does not work

### ISSUE THREAD

**Issue by freearhey** [NimitzDEV/m3u8-file-parser#3]
This can be seen already in the docs (https://github.com/NimitzDEV/m3u8-file-parser#parsing-example). All attribute names in `inf` are returned without any conversion.

**Comment by NimitzDEV** [comment]
Hi, thanks for your report, could you post some of your M3U contents here? that would be helpful to identify the problem. :)

**Comment by freearhey** [comment]
Yes of course. For example:

```
#EXTM3U x-tvg-url="http://195.154.221.171/epg/guidealbania.xml.gz"
#EXTINF:-1 tvg-ID="News 24 AL" tvg-name="News 24 AL" tvg-logo="https://i.imgur.com/PWGMnzW.jpg" group-title="News",News 24
http://tv.balkanweb.com:8081/news24/livestream/chunks.m3u8
#EXTINF:-1 tvg-id="RTSH 1 HD AL" tvg-name="RTSH 1 HD AL" tvg-logo="https://i.imgur.com/j6fL4vc.png" group-title="",RTSH 1 HD
http://79.106.48.2/live/rtsh_1ott/playlist.m3u8
```

As you can see, the `tvg-id` attribute can have a different case, as a result each segment will have a different property `inf['tvg-id']` and `inf['tvg-ID']`. But according to the documentation, both segments should only have the `inf.tvgId` property.

**Comment by NimitzDEV** [comment]
Camel case conversion for EXTINF is now live at version 0.2.2, please update your dependencies to check the result, if it meets your expectation, please close this issue 😄

**Comment by freearhey** [comment]
Yeap, I can confirm, now the conversion is working fine.
