### ISSUE TITLE
Builder support?

### ISSUE THREAD

**Issue by SamJarmanPP** [NimitzDEV/m3u8-file-parser#8]
Once parsed, can I then change a value and rebuild the m3u8 string again?

Thanks!

**Comment by NimitzDEV** [comment]
Do you mean to re-parse a specific line or the whole file?
If you want to re-parse the whole file you can call `reset()` first and then call `read()` again.
And currently no support for the specific lines to be re-parsed.

**Comment by SamJarmanPP** [comment]
No, I meant once the object is given to me after parsing, can I then change a value on the object and then serialise back out to a m3u8 file?

**Comment by NimitzDEV** [comment]
@SamJarmanPP Sorry no, this library cannot serialize it back to m3u8 string.
